version: "3.5"

networks:
  default-network:
    driver: bridge
    ipam:
      config:
        - subnet: 173.5.0.0/16

services:
  # database:
  #   container_name: mysql
  #   image: mysql:5.7
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #     MYSQL_USER: ecommerce
  #     MYSQL_PASSWORD: 123456
  #     MYSQL_DATABASE: ecommerce
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - default-network
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
volumes:
  db_data:
    driver: local
